// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	v1 "auth/internal/handler/v1"
	"auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: v1.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: v1.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: v1.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: v1.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/form/example",
				Handler: v1.FormExampleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/path/example/:id",
				Handler: v1.PathExampleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
