// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	v1 "users/internal/handler/v1"
	"users/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: v1.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: v1.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/usersaccepts",
				Handler: v1.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: v1.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:idaccepts",
				Handler: v1.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: v1.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: v1.ListRolesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
