apiVersion: apps/v1
kind: Deployment
metadata:
  name: avinya
  namespace: avinya
  labels:
    app: avinya
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: avinya
  template:
    metadata:
      labels:
        app: avinya
    spec:
      containers:
      - name: avinya
        image: 
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: avinya-svc
  namespace: avinya
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: avinya

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: avinya-hpa-c
  namespace: avinya
  labels:
    app: avinya-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avinya
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: avinya-hpa-m
  namespace: avinya
  labels:
    app: avinya-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avinya
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
