// Code generated by goctl. DO NOT EDIT.
package types

type UpdateReq struct {
	Arg1 string `json:"arg1"`
}

type ListItem struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Name string `json:"name"`
}

type FormExampleReq struct {
	Name string `form:"name"`
}

type PathExampleReq struct {
	ID string `path:"id"`
}

type PathExampleResp struct {
	Name string `json:"name"`
}
