// Code generated by goctl. DO NOT EDIT.
package types

type UserItem struct {
	Id        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Phone     string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type UserListItem struct {
	Id        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Phone     string `json:"username"`
	Email     string `json:"email"`
}
